# ------------------------------------------------------------------------------------------------
# auth-srv k8s deployment file for BigTix platform microservices E-Commerce project
# @since auth-micro-start--JP
# ------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dpl
spec:
  replicas: 1 # for now
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 1ntellijosh/bigtix-auth-srv
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongo-srv:27017/auth
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # This will be the pod name
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-url
                  key: RABBITMQ_URL

---

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
