# ------------------------------------------------------------------------------------------------
# orders-srv k8s deployment file for BigTix platform microservices E-Commerce project
# @since orders-srv-start--JP
# ------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-dpl
spec:
  replicas: 1 # for now
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 1ntellijosh/bigtix-orders-srv
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: mongodb://orders-mongo-srv:27017/orders
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # This will be the pod name
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-url
                  key: RABBITMQ_URL

---

apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
