# ------------------------------------------------------------------------------------------------
# payments-mongo-srv mongo-db k8s deployment file for BigTix platform microservices E-Commerce project
# @since payments-srv-start--JP
# ------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-mongo-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-mongo
  template:
    metadata:
      labels:
        app: payments-mongo
    spec:
      containers:
        - name: payments-mongo
          image: mongo

---

apiVersion: v1
kind: Service
metadata:
  name: payments-mongo-srv
spec:
  selector:
    app: payments-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017 # Default MongoDB port
      targetPort: 27017 # Default MongoDB port