# ------------------------------------------------------------------------------------------------
# tickets-srv k8s deployment file for BigTix platform microservices E-Commerce project
# @since tickets-srv--JP
# ------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-dpl
spec:
  replicas: 1 # for now
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: 1ntellijosh/bigtix-tickets-srv
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # This will be the pod name
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-url
                  key: RABBITMQ_URL

---

apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
